### ISSUE TITLE
[SUGGESTION] Option to re-send vote packet only on server voter is online

### ISSUE THREAD

**Issue by MeMyselfMC** [NuVotifier/NuVotifier#1]
Just like BVotifier. This feature would be great.
A config option to allow us to only re-send received vote packets to the server the voter is currently on. If the voter is offline, broadcast to X server.

**Comment by Ichbinjoe** [comment]
So only forwarding to the server the player is currently on? I could see issues with cloud based systems, however @minecrafter should probably weigh in on it as well.

**Comment by minecrafter** [comment]
@Ichbinjoe I don't feel that this could conflict with "cloud" systems.

**Comment by Ichbinjoe** [comment]
One bungee cord that receives the vote may not have the player in question on that particular bungee cord. Therefore, under what I am thinking to rectify the situation is to hold the vote until they come back online to that bungee. However, in a cloud system, another bungee may be handling the player. We could send the votes downstream, however, unless a callback mechanism was put in place, there would be no way to determine if the vote was used.

**Comment by minecrafter** [comment]
Oh, I apologize. We could add in better vote forwarding mechanisms (Redis vote forwarding?) to rectify this though.

**Comment by MeMyselfMC** [comment]
@minecrafter I guess. So would this be possible? Also EMP support would be nice, if it's a problem on NuVotifier's side.

**Comment by Ichbinjoe** [comment]
I am not sure what 'broadcast to X server' means. Is that broadcast to a fallback server?

**Comment by Ichbinjoe** [comment]
And right now, EMP support is majorly Enjin's issue. However, we could work to find a work around.

**Comment by minecrafter** [comment]
@MeMyselfMC The EMP issue is on Enjin's side, for using internal API that are liable to break at any time.

@Ichbinjoe I would assume a fallback server broadcast.

**Comment by MeMyselfMC** [comment]
Yeah, somewhat of a fallback server. So for example, there would be two new configuration options, one allowing us to specify if we want votes to be broadcasted only to the server the voter is on, and one to specify what server(s) the vote would be broadcasted to if the voter is offline.

**Comment by Ichbinjoe** [comment]
Sorry if this feels abandoned, I should find time to knock this out tomorrow.

**Comment by MeMyselfMC** [comment]
Alright.

**Comment by minecrafter** [comment]
Looks like this was abandoned.

Proxy-based forwarding works better in this case. Let me know if this resolves your issue.

**Comment by MeMyselfMC** [comment]
I don't really see how that works :stuck_out_tongue:
You could just make this a pluginMessaging option, where it only forwards the vote to the server the voter is currently on. If the voter is offline, forward the vote to X server.

**Comment by Ichbinjoe** [comment]
The issue I had encountered when designing this was the fact that some people have distributed networks, with more than one bungee. I guess I'll add a version which only works with one proxy, and add a note to this (I am assuming this is the majority of users, and users who don't fit will probably want a solution independent of us.

**Comment by Ichbinjoe** [comment]
Fixed in commit f2449790a093172be023301209ca497d39dab9a5
