### ISSUE TITLE
Request: Stand alone server for forwarding votes

### ISSUE THREAD

**Issue by Samistine** [NuVotifier/NuVotifier#10]

**Comment by minecrafter** [comment]
I was considering this, but I think this is a little too niche at the moment.

**Comment by Samistine** [comment]
Well I'm currently just running an offline bungeecord server to run this,
not too much of an issue but yea.

**Comment by Ichbinjoe** [comment]
Added in 700db6dca0397656823998f722e2cb5f7d6a5749
