### ISSUE TITLE
Error in Forwarding with Plugin Message Channel

### ISSUE THREAD

**Issue by Proplex** [NuVotifier/NuVotifier#11]
Using Bungee with Multiple Spigot servers, all with NuVotifier with Bungee acting as the external, and sending votes over to the internal NuVotifiers via plugin channels, this error occurs:

```
22:54:18 [INFO] [NuVotifier] Got a protocol v1 vote record -> Vote (from:PlanetMinecraft.com username:SparkAI address:70.214.68.14 timeStamp:1468637658)
22:54:18 [INFO] [NuVotifier] Added to forwarding cache: Vote (from:PlanetMinecraft.com username:SparkAI address:70.214.68.14 timeStamp:1468637658) -> null
22:54:28 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@6b44435b, id=3, owner=com.vexsoftware.votifier.bungee.NuVotifier@1dd0e7c4, task=com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache$1@4721d212, delay=180000, period=180000, running=true) encountered an exception
java.lang.NullPointerException: Null key.
    at com.vexsoftware.votifier.json.JSONObject.put(JSONObject.java:1138)
    at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache.save(FileVoteCache.java:73)
    at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache$1.run(FileVoteCache.java:36)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at  #java.lang.Thread.run(Thread.java:745)
```

The relevant part of my config is:

```
forwarding:
  method: pluginMessaging
  pluginMessaging:
    channel: NuVotifier
    cache: file
    joinedServerFallback: ''
    file:
      name: cached-votes.json
```

**Comment by Proplex** [comment]
Also, completely unrelated, but I've noticed that the debug value in config.yml has no effect on a bukkit/spigot server. When set to true, there is no extra debugging output, and there is no announcement that it's in debugging mode like https://github.com/NuVotifier/NuVotifier/blob/master/bukkit/src/main/java/com/vexsoftware/votifier/NuVotifierBukkit.java#L230 suggests

**Comment by Proplex** [comment]
This is rather urgent. When this error occurs, the Bungee process hangs and no longer accepts users.

**Comment by RaccoTaco** [comment]
Hey! Did you happen to solve the issue? I'm currently getting the same error, and not sure how to sort it.  The only thing is that I see the error when an offline vote comes in.

**Comment by Ichbinjoe** [comment]
Hey! I believe I solved the issue with commit 0eca96b. This will be released here soon, so hold tight!

**Comment by RaccoTaco** [comment]
Nice! I'll keep a lookout then.

**Comment by RaccoTaco** [comment]
Current Bungee Config:

`host: xxx.xx.xxx.xxx <-- Hid it
port: 8192

debug: true

tokens:
  default: ur4fdt0ahvt3d5apagov9krh4j

disable-v1-protocol: false

forwarding:
  method: proxy
  pluginMessaging:
    channel: NuVotifier
    excludedServers:
    - Hub
    cache: file
    onlySendToJoinedServer: true
    joinedServerFallback: ''
    file:
      name: cached-votes.json
  proxy:
    Reborn:
      address: xxx.xx.xxx.xxx <-- Hid it
      port: 8107
      token: di4253ccv2fj2m9s4g5i83d5kn`

**Comment by Ichbinjoe** [comment]
NuVotifier is not caching the vote since you specified to only send the vote to the joined server, however did not specify a server to send the vote to as a fallback. This may be a missed requirement - I will contemplate adding a feature to cache votes and release on join to whatever server they join to. If possible, specify a fallback server.

**Comment by RaccoTaco** [comment]
The thing is that offline voting worked prior, and I had it set at the same settings. It might have been an update these past few months that stopped the behavior. And I cannot do a fallback server since users who join start at hub which gives nothing on votes. It's only the servers you can connect from hub that give our rewards :c

**Comment by Yorkforce** [comment]
We are running into the same problem

Offline voting is not working at all, we can see the vote is received in the console when the vote is cast, but the command in the votelistener is not being run, If the player logs in afterwards, nothing happens.
We tested the cache with both file and memory settings.

If the player is online, then the command is sent and thier receive thier reward

**Comment by Ichbinjoe** [comment]
Addressing in 2.3.6
