### ISSUE TITLE
NuVotifier / GAListener Broadcast and Rewards not working

### ISSUE THREAD

**Issue by TheDangerousAsauk** [NuVotifier/NuVotifier#119]
Hello, I have been having an issue getting NuVotifier and GAListener to cooperate with each other and have a message broadcasted when someone votes. I am also having issues with GAListener not giving rewards which I know this page is for the NuVotifier plugin but I figured I would provide additional information just in case it had something to do with NuVotifier

**Comment by Ichbinjoe** [comment]
Check out this doc depending on what you are seeing:

https://github.com/NuVotifier/NuVotifier/blob/master/docs/faq.md

If you are still having issues, join our support discord: https://discord.gg/anUtuAC
