### ISSUE TITLE
StackOverflowError on initializing

### ISSUE THREAD

**Issue by Rasgnarok** [NuVotifier/NuVotifier#123]
https://gist.github.com/Rasgnarok/ec4b47a9cdf7245a1b74bd8f05e194f7
This error has been happening for a bit, but for the last 24h, now no votes are passing. Was working when I initially turned on pluginMessaging in bungee+server1+server2.
If I check server1's debug log to see for any errors, I find nothing on startup: https://gist.githubusercontent.com/Rasgnarok/6f4b72149fd36a2d4c84bb4b5dadc322/raw/058d3f5877f9d2e8a7d05a87f8ae398d3ba59128/gistfile1.txt .

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/52418663-82e86f80-2abc-11e9-84f0-4dd24059b1c2.png)
Using 2.5.0

**Comment by Ichbinjoe** [comment]
Initial error was due to an old NuVotifier version which caused the error in 2.5.0.

Delete your voting cache on bungeecord.

**Comment by Rasgnarok** [comment]
Update on this, fixed it by deleting the cache as suggested.
