### ISSUE TITLE
Connection Timed out

### ISSUE THREAD

**Issue by Coolrooswag** [NuVotifier/NuVotifier#124]
Hello! I have setup nuvotifier on my sponge server, I was using V 2.5.0 however everytime I try to send a test vote it times out, I thought it wasn't connecting to the server but it is, it just keeps timing out

https://gyazo.com/f9b197434827a4e0578889a84ef67bdf

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/blob/master/docs/faq.md#i-voted-or-submitted-a-test-vote-and-nothing-happened-why-isnt-it

Check out that FAQ. It is 100% something within that list.
