### ISSUE TITLE
not able to bind to {}

### ISSUE THREAD

**Issue by kazeookami** [NuVotifier/NuVotifier#128]
[Votifier NIO boss/ERROR]: [Votifier] Votifier was not able to bind to {}

I have followed multiple set up tutorials just in case I missed some step. I've tried using more than a dozen different ports. I keep getting this response.  I do have a listener in, SuperbVote. I am unsure what else this error may be wanting from me, really.

**Comment by Ichbinjoe** [comment]
If you are on your own host, your bind ip is probably wrong.

If you are on a shared host, contact your host for a port allocation.
