### ISSUE TITLE
nuvotifier doesn't detect when a user votes

### ISSUE THREAD

**Issue by SlendyOff** [NuVotifier/NuVotifier#129]
Hello, i have a problem with the votes, i tested in this page https://mctools.org/votifier-tester and nothing happends in the console and ingame i don't know if i setup wrong i'm new in this 

my configuration:
debug: true
port: 7051
host: 127.0.0.1
tokens: {default: (The token)}
disable-v1-protocol: false
forwarding:
    method: none
    pluginMessaging: {channel: 'nuvotifier:votes'}

Console log:
[K[33;1m[19:18:01] [Server thread/WARN] [Sponge]: Plugin 'nuvotifier' seems to be missing a valid mcmod.info metadata file. This is not a problem when testing plugins, however it is recommended to include one in public plugins.
Please see https://docs.spongepowered.org/master/en/plugin/plugin-meta.html for details.
[K[19:20:00] [Server thread/INFO] [nuvotifier]: Loaded token for website: default
> 
[K[19:20:00] [Server thread/INFO] [nuvotifier]: DEBUG mode enabled!
>
[K[19:20:00] [Server thread/INFO] [nuvotifier]: Method none selected for vote forwarding: Votes will not be received from a forwarder.
>

**Comment by Ichbinjoe** [comment]
So the main problem is that your host is bound locally - you should be using 0.0.0.0

Secondly, if you tried that in the past, we would need to know more about your hosting setup.

**Comment by SlendyOff** [comment]
now ty
