### ISSUE TITLE
Votifier does not work!

### ISSUE THREAD

**Issue by PhantomMarth** [NuVotifier/NuVotifier#13]
Currently I am using the listener VoteRight, and when I type /vr sim, it works! But when I click and vote on the website it does not work! I change the ip in the config to the original and 0.0.0.0 and nothing happens. I get no error report!

**Comment by Ichbinjoe** [comment]
Please post your configurations. It could also be your port is firewalled. Ensure there are no stack traces within your start up log. I do not believe this is an issue with NuVotifier.

**Comment by PhantomMarth** [comment]
# The IP to listen to. Use 0.0.0.0 if you wish to listen to all interfaces on your server. (All IP addresses)
# This defaults to the IP you have configured your server to listen on, or 0.0.0.0 if you have not configured this.
host: 162.252.85.196
# Port to listen for new votes on
port: 8192

# Whether or not to print debug messages. In a production system, this should be set to false.
# This is useful when initially setting up NuVotifier to ensure votes are being delivered.
debug: false

# Setting this value to false will turn off the votifier port listening for external votes. This is beneficial if the server
# is only listening for votes coming from NuVotifier running on your BungeeCord.
enableExternal: true

# Setting this option to true will disable handling of Protocol v1 packets. While the old protocol is not secure, this
# option is currently not recommended as most voting sites only support the old protocol at present. However, if you are
# using NuVotifier's proxy forwarding mechanism, enabling this option will increase your server's security.
disable-v1-protocol: false

# All tokens, labeled by the serviceName of each server list.
tokens:
  # Default token for all server lists, if another isn't supplied.
  default: k9piru72sh7vpndia5vf1drk5u

# Configuration section for all vote forwarding to NuVotifier
forwarding:
  # Sets whether to set up a remote method for fowarding. Supported methods:
  # - none - Does not set up a forwarding method.
  # - pluginMessaging - Sets up plugin messaging
  method: none
  pluginMessaging:
    channel: NuVotifier

Those are my configuration

**Comment by PhantomMarth** [comment]
Do I have to do any with the StarAPI add on?

**Comment by minecrafter** [comment]
Please use [gist](https://gist.github.com) to paste your configuration.

**Comment by PhantomMarth** [comment]
https://gist.github.com/PhantomMarth/be7c1051a8ca7a2379cd762c597168f7 That is the link

**Comment by Ichbinjoe** [comment]
Ensure 8192 is not firewalled.

**Comment by PhantomMarth** [comment]
How do I check that?

**Comment by PhantomMarth** [comment]
I went to this website https://www.minestatus.net/votifier/test and tested and everything was a success. Also with the listener I am using currently is VoteRight, and when I simulate the voting it works.

**Comment by minecrafter** [comment]
Closing issue due to age.
