### ISSUE TITLE
Ipv6 not supported

### ISSUE THREAD

**Issue by Murgator** [NuVotifier/NuVotifier#131]
Hi there ! When my players (with an ipv6 address) vote on a minecraft servers list, the website send an ipv6 to votifier.

But in Minecraft the displayed IP is an ipv4, so ipv6 players do not get their reward...

Is Minecraft incompatible with ipv6 ?

Must the Minecraft servers list force voters to connect with an ipv4 ?

Thank you in advance for your answers.

David M.

**Comment by Ichbinjoe** [comment]
I'm not completely sure what you are asking here so I'll try my best.

NuVotifier doesn't try to match up the vote it gets (regardless of ipv4/ipv6 status) with players (again, regardless of v4/v6). There isn't any logic that does that. You may be asking about the IP transmitted within the Vote packet , which NuVotifier doesn't care about except to hand to whatever vote listeners you have installed.

If this doesn't answer your question, feel free to join the support discord.
