### ISSUE TITLE
Not processing votes at all

### ISSUE THREAD

**Issue by SilverSleet645** [NuVotifier/NuVotifier#135]
I am using nuvotifier v2.5.0 on my bungeecord and spigot servers. I use mctools.org to test votifier that I set it up correctly. When I send a test vote there, it works without any issues at all. No errors! But, when I send a vote from minecraftservers.org (using the same key obv), it gives me this error: https://pastebin.com/nusRh3w4
Please help I need to get voting working on my server asap!
Thanks
 - SilverSleet

**Comment by Ichbinjoe** [comment]
So like, I understand that you used the same key.

But I'm not going to start doubting the crypto here. We physically cannot read the voting information if the key is incorrect / the data is corrupted. It straight up 100% does not work. While I would like to fix this for you without having the right key as debug, with votifier v1, I can't.

Absolutely double check your rsa public and private keys. Make sure you didn't modify either file.
