### ISSUE TITLE
Plugin will not start in Sponge due to mismatched dependencies

### ISSUE THREAD

**Issue by zerafox** [NuVotifier/NuVotifier#136]
**NuVotifier** 2.5.2
**Minecraft** 1.12.2
**SpongeAPI** 7.1.0-3fdbf299
**Sponge** 1.12.2-7.1.6-SNAPSHOT
**SpongeForge** 1.12.2-2825-7.1.6-RC3708
**Minecraft Forge** 14.23.5.2825

NuVotifier does not appear to be loading properly.
Vote-Sites claim to be connecting _(Though the host I use requires adding and opening a new port on the server itself directly)_, however no vote actually reaches the console or vote-reward plugin.
Tested several times, no results.

Only found this in the console logs relating to NuVotifier: https://pastebin.com/Rf86zqTU
It is the same error in debug.log as well.

This used to work prior to a recent map reset.
No changes were made to the server's IP, Port, NuVotifier files in any form prior or after the map reset.

**Comment by Ichbinjoe** [comment]
Looks like this was caused by a recent change to Sponge packaging. I will investigate when I have more time.
