### ISSUE TITLE
won't bind to IP?

### ISSUE THREAD

**Issue by Dracathio** [NuVotifier/NuVotifier#137]
So I get this error for some reason
I haven't a clue as to why.

ERROR Votifier was not able to bind to /107.174.235.202:8192

I'm running a 1.13.2 server with latest version of NuV
I am also using latest 1.13.2 version of paper spigot.

**Comment by Ichbinjoe** [comment]
Contact your host. This is due to either your host locking the port or you have another instance running on that port.
