### ISSUE TITLE
Whole server lags when some one votes, can even crash.

### ISSUE THREAD

**Issue by MithrandirCraft** [NuVotifier/NuVotifier#143]
Every time someone votes, the server lags for around 15 seconds.
After a vote reception the server can even crash.

Crash log: https://pastebin.com/Q4wCdnsg
(It's incomplete, I can provide it entirely if requested)

NuVotifier version: 2.5.0 (still says it's Votifier instead of NuVotifier, also I think I'm kinda outdated so I will try to find a newer build of your plugin, however I still wanted to report this.)

**Comment by Ichbinjoe** [comment]
Looks like the Enjin plugin is actually causing the lag.

**Comment by Favorlock** [comment]
@Ichbinjoe The line in question https://github.com/enjin/Enjin-Minecraft-Plugin/blob/master/bukkit/src/main/java/com/enjin/bukkit/listeners/VotifierListener.java#L44

Would that really cause lag capable of crashing?

**Comment by Ichbinjoe** [comment]
So the fact its a closing bracket suggests that the version OP is running a different version then latest master.

**Comment by Ichbinjoe** [comment]
https://github.com/enjin/Enjin-Minecraft-Plugin/blob/2cc543ae691a7a2bf140f85f6c58a031838d5ee5/bukkit/src/main/java/com/enjin/bukkit/listeners/VotifierListener.java#L44

So for reference, yes it could cause lag capable of crashing. getPlayer for an offline player will result in an external service lookup blocking the thread.

**Comment by Favorlock** [comment]
Ah, ok. I changed things to work much like they did in EMP 2.x, or can getOfflinePlayer also perform external service lookups?

**Comment by Ichbinjoe** [comment]
This will still trigger the external lookup in the case that the server doesn't know about the player. It is suggested and common practice to wrap these sorts of calls in an async block.

**Comment by Favorlock** [comment]
Ah, ok. That's what I was just working on doing since I figured that may be the case.

**Comment by MithrandirCraft** [comment]
@Favorlock I now updated to 3.5.6
Please let me know if I should update to something newer.

**Comment by Favorlock** [comment]
@MithrandirCraft See https://github.com/enjin/Enjin-Minecraft-Plugin/issues/6#issuecomment-500657192

The 3.5.6 on spigot doesn't have the changes regarding this issue. That'll come in the next update. I did link to a development build that I uploaded to google drive, so you can get the updated version early to test if you'd like.
