### ISSUE TITLE
IP Change ?

### ISSUE THREAD

**Issue by Feutor** [NuVotifier/NuVotifier#146]
My IP in the config.yml changed to 0.0.0.0 for some reason. Now none of the votes are coming through, even after manually changing the IP.
EDIT: After further investigation, the IP didn't matter as I realized that 0.0.0.0 just means, itll use any server interface but still, about 7 hours ago, our vote forwarding stopped working completely and I have no idea how to fix it.

**Comment by Ichbinjoe** [comment]
The plugin will not opportunistically reset the IP in an existing configuration. The only case where that IP will be set to 0.0.0.0 is when 1) its a new configuration and 2) nuvotifier can't figure out what the correct bind ip is.

You should send more details about your forwarding setup in the support discord.
