### ISSUE TITLE
Large cache files?

### ISSUE THREAD

**Issue by L4BORG** [NuVotifier/NuVotifier#15]
So I've been looking into this because we were having issues with high CPU load on our BungeeCord lately. Now, we're using "cache: file" for awhile now and it just caught my eye that cached-votes.json is 130MB (and it's only about 1 or 2 months old).

Also I would say that most of that data there is useless (inactive players, etc) and it would be a good idea to have some kind of TTL (simple timestamp would do that job) and of course a task that would purge old data.

**Comment by minecrafter** [comment]
I will implement this in a later release.

**Comment by minecrafter** [comment]
I've committed a temporary patch which does not work around the problem but should at least ameliorate the issue for starting the proxy.

**Comment by Ichbinjoe** [comment]
Addressing in 2.3.6
