### ISSUE TITLE
Chanche HOST and update to 1.14.4

### ISSUE THREAD

**Issue by SrBedrock** [NuVotifier/NuVotifier#152]
Hi,
After switching hosts and upgrading to version1.14.4, the plugin do not announce votes.
Could you help me figure out what I did wrong?

Server version: git-Paper-146 (MC: 1.14.4)

NuVotifier log: https://hastebin.app/1564256807958
NuVotifier config.yml: https://pastebin.com/WgFsffnT
NuVotifier Version: 2.5.3

SuperBVote config.yml: https://pastebin.com/DkfvMyaK
SuperBVote Version: 0.5.4

**Comment by Ichbinjoe** [comment]
Probably a configuration error. Looks like NV enabled fine. 

The plugin requires no changes to be run on 1.14.4.
