### ISSUE TITLE
Neither PUB key nor PRIV key: header too long

### ISSUE THREAD

**Issue by s1h4d0w** [NuVotifier/NuVotifier#153]
So I've tried several Votifier test pages to see if NuVotifier was working, but they all return this:

```
Fail!There was an issue sending a notification to Votifier on 54.37.246.172:25566.
This was the exception that occurred internally: Neither PUB key nor PRIV key: header too long
```
I have double checked if I've entered all the information correctly, and that the public key was correct, with no spaces in front or behind it, etc.

Is this an issue on my end with the port not being open, or something else? The error made me think it might be some other issue.

**Comment by Ichbinjoe** [comment]
Uh the error says that the key you handed it didn't look like a public key or private key. I don't know the tool you are using, so I can't help with using it. 

Make sure you are using the key in rsa/ not a token.

**Comment by s1h4d0w** [comment]
I was just about to close the issue, my apologies. It seems that I was using the token in place of the public key. All working now, thank you!
