### ISSUE TITLE
NuVotifier resetting on PlanetMinecraft

### ISSUE THREAD

**Issue by GottaSlay** [NuVotifier/NuVotifier#156]
Hey. I have NuVotifier set up and it works properly on 3 sites out of 4. But the 4th one doesn't work which is planetminecraft. Everytime i put in the right port number and our IP as well as the public key and go to save. The votifier settings in planetminecraft have reset to completely wrong settings?

**Comment by Ichbinjoe** [comment]
Sounds like a PMC problem. Go bug PMC.
