### ISSUE TITLE
Update to 5.0/6.0 API please?

### ISSUE THREAD

**Issue by ProsperCraft** [NuVotifier/NuVotifier#16]

**Comment by Ichbinjoe** [comment]
NuVotifier already statically builds after updating the API to 5.0. NuVotifier also uses an extremely small portions of the Sponge, Bukkit, and BungeeCord APIs.

Is NuVotifier throwing a certain error, or any indication that it doesn't actively work? I am not familiar with Sponge development, and any assistance would be appreciated.

**Comment by hunter688** [comment]
Im testing nuvotifier with latest sponge, works without problems.

**Comment by ProsperCraft** [comment]
You can update the plugin page, it works great with 5.0/6.0 API as it stands.
