### ISSUE TITLE
Bungee pluginMessaging Not working

### ISSUE THREAD

**Issue by Beckstation** [NuVotifier/NuVotifier#160]
I have a single proxy for bungee, and then 3 servers. HUB, Faction, Survival. 
Hub is ignored, but has the votifier installed, simply in the ignored list of the proxy. 

Factions and Survival are setup according exactly to your setup guide. Same for the proxy server. 

I can test votes using Mctools, and the vote goes through. However, I get no indication of info in the consoles of any of my servers stating that its working or a vote was registered. I also do not get any info from votes when using vote sites. There are no rewards from my reward plugin either. Nothing.

According to a documentation theres a debug mode for the votifier ? I cannot find this in any config and nor could the support for my hosting either. According to our support team everything is setup fine, and they can test votes with no issues. But nothing is coming through via consoles or logs. 

Please advise on what I can or should be doing. I can provide info or logs if you need.

**Comment by Ichbinjoe** [comment]
As of latest release, debug mode is always on and the option was removed from the config.

This sounds like a configuration error. I do not give free support for any of my work. Please read the notice here: https://www.spigotmc.org/resources/nuvotifier.13449/

If you have information which makes it not a configuration error (such as an unexpected stack trace) please post it.

**Comment by Beckstation** [comment]
I understand you do not give support, however I've had 2 different server support agents go over our config and setup following your own guidelines and its not working. 

They purely suggest contacting yourself for support as they do not know why its not working.
