### ISSUE TITLE
onlySendToJoinedServer not sending when player comes online

### ISSUE THREAD

**Issue by PhanaticD** [NuVotifier/NuVotifier#162]
with onlySendToJoinedServer: true, I voted while offline, then joined the server and did not get a vote forwarded to spigot server. With the option set to false it did work

**Comment by Ichbinjoe** [comment]
Ya sounds like a bug. Can you share your bungee config and logs please - I trust you are able to know how to redact the right things

**Comment by Ichbinjoe** [comment]
No logs / repro. Closing.
