### ISSUE TITLE
Closing my issue unresolved.

### ISSUE THREAD

**Issue by SilentRoses** [NuVotifier/NuVotifier#165]
Original issue: https://github.com/NuVotifier/NuVotifier/issues/164

![image](https://user-images.githubusercontent.com/45537340/71428488-fc7b5300-26b8-11ea-9f4e-4116e247831a.png)
used the same jar since june and used the direct link to download it directly from spigot so no chance its the experimental build?

**Comment by SilentRoses** [comment]
I've only ever used 2.5.3 so god knows wher you got the 3.0.0 from? None of my configs say 3.0.0 nor do any of my jars?

**Comment by Ichbinjoe** [comment]
From Bungee.log line 191:

[21:07:29] [main/INFO]: Loaded plugin NuVotifier version 3.0.0-SNAPSHOT by Ichbinjoe, blakeman8192, Kramer, tuxed

In addition, please read that I DO NOT PROVIDE SUPPORT THROUGH GITHUB.

**Comment by SilentRoses** [comment]
Can you please stop closing the issue? There is literally no way im running 2.5.3

**Comment by SilentRoses** [comment]
"In addition, please read that I DO NOT PROVIDE SUPPORT THROUGH GITHUB." fair enough i understand but literally i'm not running 2.5.3

**Comment by SilentRoses** [comment]
i can legit show u in a call if u want proof

**Comment by Ichbinjoe** [comment]
https://www.spigotmc.org/resources/nuvotifier.13449/ < My policy on providing support in general.

**Comment by SilentRoses** [comment]
yeah but support from the developer is nice? especially when its telling you im running a later version than i am...? This seems like a bug not just an issue?

**Comment by SilentRoses** [comment]
Look i understand its christmas and you probably don't wanna be doing this stuff during christmas time so it's fine. Have a nice christmas.

**Comment by SilentRoses** [comment]
also fyi the plugin your providing via YOUR spigot page is apparently 3.0.0 so this seems like an error on your end.

**Comment by Ichbinjoe** [comment]
I will fix the tagging issue.

Have you even bothered to look at the troubleshooting guide? It talks about this sort of issue in it. I'm absolutely sure your problem is discussed in there. Quite frankly, this sort of thing is exactly why I stopped providing support. I have spent dozens of hours of my own time for _free_ providing this plugin to the community.

**Comment by SilentRoses** [comment]
I'm literally willing to pay for support if i have to.

**Comment by SilentRoses** [comment]
I've read the guides

**Comment by SilentRoses** [comment]
FULLY however none specify what to do if your server is running on a single proxy with a custom url

**Comment by SilentRoses** [comment]
If i missed a bit my bad and i apologise however i feel im scoured it now.

**Comment by SilentRoses** [comment]
And look i'm sorry if i'm being a pain i truly am i don't wanna piss ya off on christmas i'm grateful for your amazing work honestly i am.

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Setup-Guide#single-proxy-bungeecordvelocity-networks

It literally describes step by step what to do in your single proxy setup. First step is to stop using proxy mode and use plugin messaging which is far easier.

https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#which-forwarding-mode-should-i-use

Describes when you should be using proxy mode vs plugin messaging mode

https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#proxy

Warns you that you should only be using proxy mode if you absolutely have to.
