### ISSUE TITLE
honestly can't get this to work, hoping you could help

### ISSUE THREAD

**Issue by Danny9865** [NuVotifier/NuVotifier#166]
if you could shed some light on this it would be great

![image](https://user-images.githubusercontent.com/58650168/71640068-392be900-2c7b-11ea-9ca5-46afbd08500d.png)

![image](https://user-images.githubusercontent.com/58650168/71640075-4c3eb900-2c7b-11ea-8c5a-a5299e0ae98b.png)

![image](https://user-images.githubusercontent.com/58650168/71640089-8445fc00-2c7b-11ea-9f69-abaf83c3f6da.png)

![image](https://user-images.githubusercontent.com/58650168/71640102-af305000-2c7b-11ea-91f2-5c66e11e782e.png)

stumped at this point, port forwarded it. just cant get it to link. host is our server ip

**Comment by Ichbinjoe** [comment]
https://www.spigotmc.org/resources/nuvotifier.13449/

Please see the spigot listing for troubleshooting guides as well as my policy on support.
