### ISSUE TITLE
Having an issue here, got the ports and everything configured, sent a test which came back clean, but its still not broadcasting votes, or forwarding it to serious vote.

### ISSUE THREAD

**Issue by varnithian97** [NuVotifier/NuVotifier#167]
Attatched is the code from the begining for seriousvote and the port let me know if you want me to send the whole thing. Im honestly not too familiar with sponge, i started on bukkit but everyone was telling me the developer support, and configurability with RLcraft was top notch. But this is really stressing me out why i cannot get it to work!

I grabbed two sections in the console which were speaking about the plugins. Let me know if additional data is needed.

https://github.com/varnithian97/filebin.git

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/issues/166#issuecomment-570070395
