### ISSUE TITLE
Can't process vote

### ISSUE THREAD

**Issue by michal12sk** [NuVotifier/NuVotifier#17]
Hi I'm using BungeeCord and whenever I vote or test the voting it says 
[SEVERE] [NuVotifier] Unable to process vote from /ipadresshere:port
I copied the token onto Lobby's config from BungeeCord. Was I suposed to do that?

**Comment by stoi2m1** [comment]
I was getting this same error and last night I changed
`enableExternal: true`
on all my bukkit servers to fix the issue
