### ISSUE TITLE
NuVotifer and VotingPlugin not giveing rewards

### ISSUE THREAD

**Issue by Spooonnn** [NuVotifier/NuVotifier#172]
Hi just got NuVotifier and VotingPlugin installed and should be all set up correctly, but when I got to vote on one of the voting sites, VotingPlugin does not listen and give rewards/messages like it should. I spoke to support of VotingPlugin and he did not provide support. Everything is up to date. I have also watched Shockbytes videos on this subject. Please keep in mind this is a BUNGEE server. I have all plugins installed on my bungee serer and my other 2 spigot servers. I did use a voting tester tool and everything seems to work fine but voting rewards/messages don't go through.

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/issues/166#issuecomment-570070395
