### ISSUE TITLE
Extended developer documentation

### ISSUE THREAD

**Issue by thecodeah** [NuVotifier/NuVotifier#175]
The `Developer documentation` section in the wiki only states how to add NuVotifier as a dependency. It doesn't have any usage examples though.

After a bit of digging I found this: https://github.com/vexsoftware/votifier/wiki/Vote-Listeners-and-VotifierEvent

However, this is documentation for the old Votifier from 2012. Is this still the way to do things now? If that's the case, I still believe that this repo should have it's own documentation to minimize confusion. Or at least redirect users to the other wiki.

**Comment by Ichbinjoe** [comment]
Yeah, that's how things still happen.

Wiki is open. Be the change you want to see in the world.
