### ISSUE TITLE
Not reviving votes on one of my servers because of NUvotifier 

### ISSUE THREAD

**Issue by Spooonnn** [NuVotifier/NuVotifier#176]
Versions
Votingplugin 5.20.8 Spigot 1.15.2 and Most recent of NUvotifer

https://pastebin.com/9cTDt9mq

I am not getting the voting rewards on my main server, but getting it on my fallback server (Im running bungee and spigot) Im not really sure why but it was working before and it just suddenly stopped. This has happened multiple times. Also I forgot to add, I would put something onto the pastebin about the consoles error message, but there isn't one at all. It also seems to be only working on one spigot server only. The pastebin is of the one that isn't working.

**Comment by Spooonnn** [comment]
Now it stopped working on all of my servers...

**Comment by Ichbinjoe** [comment]
Could be a variety of things. VotingPlugin config is useless. Did you used to get NuVotifier logs from when it did work? Go back and check logs.

**Comment by Ichbinjoe** [comment]
Yeah idk comment if you have real logs and some cause other than 'it just suddenly stopped'. This plugin has had years of battle tested production use across thousands of servers. Github issues aren't a place for support.
