### ISSUE TITLE
Unable to send vote

### ISSUE THREAD

**Issue by theTexxt** [NuVotifier/NuVotifier#177]
I'm using NuVotifier for BungeeCord and 2 spigot servers. When I try to send vote it doesn't working and an error in console "unable to send vote to /IP:PORT" how can I fix it?

**Comment by plebexer** [comment]
same here, im pulling my hair

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide
