### ISSUE TITLE
Couldn't bind my port

### ISSUE THREAD

**Issue by AccioAce** [NuVotifier/NuVotifier#178]
Hello, 
Nu Votifier seems to be having some kind of trouble where my IP and Port isn't binding. So my voting system isn't working. I have tried allocate the port but that didn't help it either. It used to worked find for me when I just had SSH. Right now I am using pterodactyl panel for the first time and seems to be having issue. I believe is the panel that interfering the binding IP/Port or would you what kind of issue that may cause it?

Screenshot: https://imgur.com/a/IXFgNcE 

- Thanks

**Comment by astei** [comment]
Please read the [wiki](https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#i-voted-or-submitted-a-test-vote-and-nothing-happened-why-isnt-it-working). You probably aren't doing something correctly in your channel. There is no NuVotifier issue here, closing.
