### ISSUE TITLE
Does forwards, but public-key wrong

### ISSUE THREAD

**Issue by Jamie4224** [NuVotifier/NuVotifier#18]
I'm using NuVotifier on my bungee server, and normal Votifier on my proxied servers. But it's not working in the console of the proxied server it says the rsa public is wrong. But its not.

NuVotifier config: [Config](http://pastebin.com/wtphtGft)

**Comment by minecrafter** [comment]
You need to use NuVotifier on your proxied servers as well.

**Comment by Jamie4224** [comment]
But is NuVotifier compatible with GAListener?

**Comment by minecrafter** [comment]
Yes, it is.
