### ISSUE TITLE
vote not reading on all but one site

### ISSUE THREAD

**Issue by threlief** [NuVotifier/NuVotifier#180]
i have set up votifier before and only problem i had was a missed space or a extra letter but for some reason since i swapped host i cannot get the votes to work at all i would like help please also almost all have the same ip from the same host but different ports this comes up and i tried changing port but still same error my first server works and sends votes just fine :/  [Votifier NIO boss/ERROR]: [Votifier] Votifier was not able to bind to /158.69.23.62:2235

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#i-voted-or-submitted-a-test-vote-and-nothing-happened-why-isnt-it-working
