### ISSUE TITLE
NuVotifier Vote Forwarding Breaks on Subserver Crash Bug

### ISSUE THREAD

**Issue by Max604** [NuVotifier/NuVotifier#181]
Hi,

I'd like to report a bug. With my setup I have identified that if my creative server crashes and comes back online, the vote (v1 protocol) will no longer be forwarded to the creative server when its received from the bungee server.

I am currently using the most up-to-date public build. I haven't tried using a dev build.

Wiki and Troubleshooting pages have been consulted thoroughly.

Thanks.

**Comment by Ichbinjoe** [comment]
There is an explicit hook waiting for the server to come back. Logs from all servers surrounding the time of the disconnect & reconnect?

**Comment by Max604** [comment]
I will monitor the next time it occurs, analyse it and post it back here with my findings.

Thanks

**Comment by astei** [comment]
No response on this issue for a while, so I'm closing it. If you still have this issue please let us know and we can take a further look.
