### ISSUE TITLE
V3 Question

### ISSUE THREAD

**Issue by J3fftw1** [NuVotifier/NuVotifier#182]
Hey,

We saw there was some work on V3 over on the [refator branch](https://github.com/NuVotifier/NuVotifier/tree/refactor) and saw some discussion on this [Spigot thread](https://www.spigotmc.org/threads/362037/).

Is there a solid design for the new V3 protocol yet? Would be nice to implement for testing in the future.

(Also, sidenote, in V2 if you add a Json Object to "payload" rather than adding the JSON as a String it throws a UnsupportedOperationException.)

**Comment by Ichbinjoe** [comment]
I haven't had time to implement or design V3. I would really like to, but my priorities are in other places.

Also yeah that second part is probably a bug, but I don't think it will cause incorrect behavior so isn't a super high priority.

**Comment by J3fftw1** [comment]
Very fair, thank you for your work!

**Comment by astei** [comment]
Closing this issue as the question has been solved.
