### ISSUE TITLE
Need new keys

### ISSUE THREAD

**Issue by neonwynd** [NuVotifier/NuVotifier#186]
I transfered all files from my old server to a new one, everything works great except nuvotifier. the websites are sending the votes to my server, but im getting an error code:
Votes are now getting recived from the vote servers but this happens. [13:30:50 ERROR]: [Votifier] Unable to process vote from /149.202.74.183:46432 Go update the keys on the lists
[13:30:50 ERROR]: [Votifier] Unable to process vote from /149.202.74.183:46432
com.vexsoftware.votifier.netty.handler.codec.CorruptedFrameException: Could not decrypt data (is your key correct?)

**Comment by darbyjack** [comment]
Backup the directory, delete it, let it regen. Use that key on the voting site.

**Comment by astei** [comment]
The GitHub is not to be used for support. @darbyjack has provided the instructions for resetting the keys.
