### ISSUE TITLE
Plugin not loading in, even with GAListener

### ISSUE THREAD

**Issue by SaintGearz** [NuVotifier/NuVotifier#187]
https://gist.github.com/SaintGearz/dc8d8594f2d00bb1f08fb41a8be13c8c

**Comment by astei** [comment]
You're running some Bukkit 1.7.10 derivative - what is it?

**Comment by SaintGearz** [comment]
> You're running some Bukkit 1.7.10 derivative - what is it?

I am running thermos 1.7.10 under infinity evolved modpack

**Comment by astei** [comment]
Looks like the easiest way to fix the problem is to stop depending on Guava as it's too much of a moving target for implementations.

**Comment by SaintGearz** [comment]
erm pretend im a noob xD, how would i do that?

**Comment by astei** [comment]
I have to do it.

**Comment by SaintGearz** [comment]
Oh alright, well I will be awaiting for your response good sir

**Comment by astei** [comment]
As of the latest commit, all use of Guava in the plugin has been removed. This will greatly improve compatibility.

I will be releasing 2.7.0 once I'm confident #170 is fixed.
