### ISSUE TITLE
PluginMessaging Not working for me

### ISSUE THREAD

**Issue by plebexer** [NuVotifier/NuVotifier#189]
hey i currently want to send my votes only to one server, so i wanted to set up the plugin with PluginMessaging, i tried sending test votes from a page, and the proxy says it received the vote,  when i join to the server, it says it send the vote sucsessfully, but nothing is there (im using votingplugin)
And then if i send the vote again while being in the server, the plugin just tries to foward the vote to every other server except for the one im already connected, and no one can receive votes, i even tried with the lastest dev versions and i cant make it work

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide

And re-read the configuration guide: https://github.com/NuVotifier/NuVotifier/wiki/Setup-Guide#plugin-messaging-based-forwarding
