### ISSUE TITLE
On every vote server stops

### ISSUE THREAD

**Issue by Andoz** [NuVotifier/NuVotifier#190]
Hello,
I have an issue and I don't know wich one of these plugins makes it stops on vote, possible are: **Skript**, **CMI** and **nuVotifier**..

My error is here: [pastebin.com/zfMsxd3p](https://pastebin.com/raw/zfMsxd3p)

I have tried using new version of Skript but it didn't worked..
Thank you for your support and time :)

**Comment by astei** [comment]
NuVotifier is 100% not the problem, I assure you.
