### ISSUE TITLE
When voting, Could not decrypt data (is your key correct?)

### ISSUE THREAD

**Issue by XDLang** [NuVotifier/NuVotifier#193]
Running Bungeecord with latest NuVotifier

**Description**  
When someone votes, I get this error in the Bungeecord console: Could not decrypt data (is your key correct?). I have tried many different voting sites, Resetting the secret key and nothing. It does seem to forward the votes sometimes but rarely.

**Steps to reproduce**  
Paste your voting info in a vote tester or a Minecraft server listing site which then sends the vote to the Bungeecord proxy.

**Expected behavior**  
Forwards votes to the Spigot servers

**Comment by astei** [comment]
You didn't enter the key correctly or are using the wrong key. This is covered in the troubleshooting guide.

https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#i-voted-or-submitted-a-test-vote-and-nothing-happened-why-isnt-it-working
