### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Volgeop** [NuVotifier/NuVotifier#194]
### Information

**Platform on which you run NuVotifier**: 
Paper
**Version of NuVotifier**: 
v2.6.0

https://gist.github.com/Volgeop/ccdc00734bf6529b26958c82416aa831
### Details

**Description**  
In console is this error.... that's all I know.

**Steps to reproduce**  
I just looked into console today and there was this error.

**Expected behavior**  
Console without errors.

**Comment by astei** [comment]
You're not running Paper, but I'll put that aside. This is definitely a bug, but it's one that should be fixed in the next version already due to some unrelated changes (2.7.0).

Can you please verify the issue is fixed by running [a dev build](https://ci.velocitypowered.com/job/NuVotifier/)?

**Comment by Volgeop** [comment]
Oh sorry it was Waterfall 😅. And yes probably fixed, if happens again I will let you know.
