### ISSUE TITLE
Bungee Error

### ISSUE THREAD

**Issue by LoSCraft-Network** [NuVotifier/NuVotifier#195]
### Information

**Platform on which you run NuVotifier**: 
BungeeCord (Aegis)
**Version of NuVotifier**: 
2.6.0

**Relevant log**: 
### Details
https://pastebin.com/ZMebgXEq
**Description**  

Happens when a player joins, not every time tho
**Steps to reproduce**  

Player joined
**Expected behavior**  

No error

**Comment by astei** [comment]
Already fixed in a [dev build](https://ci.velocitypowered.com/job/NuVotifier/).

Also, don't use that Aegis garbage if you know what's good for you. We don't test on that.
