### ISSUE TITLE
Updated from version 2.4.1 to 2.7.0 now Nuvotifier doesn't work correctly.

### ISSUE THREAD

**Issue by DankPrison** [NuVotifier/NuVotifier#196]
**Version of NuVotifier**:  2.7.0

Bukkit: 1.13.2

BungeeCord: Latest available from spigotmc.org

**Relevant log**: https://gist.github.com/DankPrison/7745c20701e30b8104babd70110abb10

**Description**   Used 2.4.1 for years. Upgraded to 2.7.0 now none of my votes are going through

**Steps to reproduce**  Used 2.4.1 for years. Upgraded to 2.7.0 on both Bungeecord and Spigot server

**Expected behavior**  Votes to work correctly.

**Comment by astei** [comment]
Thanks for reporting this issue, it should be fixed now. I will cut a 2.7.1 version now.

**Comment by astei** [comment]
NuVotifier 2.7.1 is now released with the bug fix.

**Comment by DankPrison** [comment]
@astei Thank You!
