### ISSUE TITLE
Could not decrypt data

### ISSUE THREAD

**Issue by ItsSynchro** [NuVotifier/NuVotifier#197]
### Information

**Platform on which you run NuVotifier**: PaperSpigot 1.15.2

**Version of NuVotifier**: 2.7.1

**Relevant log**: https://hasteb.in/siciviri.lua
### Details

**Description**  
NuVotifier appears to throw an error whenever a player attempts to vote

**Steps to reproduce**  
Not entirely certain.

**Expected behavior**  
Allowing the vote to be sent/recieved.

**Comment by astei** [comment]
Unable to reproduce, may a problem with the site you're using sending garbage data
