### ISSUE TITLE
High CPU Usage and RAM Usage

### ISSUE THREAD

**Issue by nagasiminecraft** [NuVotifier/NuVotifier#198]
I read on other forum it said epoll make cpu goes very high when vote is stuck. but idk, when i tried remove nuvotifier cpu usage is normal again
![image](https://user-images.githubusercontent.com/34377372/86703298-52f12300-c046-11ea-897d-fddec0423739.png)

**Comment by astei** [comment]
You did not follow the template. What causes the "vote is stuck"? You didn't even name the "other forum". Further, there are other factors that can increase CPU usage. Please actually provide information instead of trying to have me guess what is going on.

**Comment by astei** [comment]
No response in over 2 weeks, so I'm closing this.
