### ISSUE TITLE
Vote Not Dispersing on Bungee Network, Also Error

### ISSUE THREAD

**Issue by TheMattVid** [NuVotifier/NuVotifier#2]
This is probably not an issue with the plugin, but just some troubleshooting with the way I am setting things up. I'm not 100% sure about how the plugin's underlying system works, but I guess I have a basic idea.

My intent was to set up NuVotifier for my Bungeecord network. I put the NuVotifier plugin into the plugin folders of all of the individual servers, as well as Bungeecord. Then I restarted. Everything generated properly. I have OnTime as my listener. It is easily able to count the votes each player makes. I assume that I was supposed to use the IP and public key from Bungeecord on the voting websites. Anyway, those websites said they successfully connected. I had to change the port In the Bungee config to 8000 due to the hosting.

For awhile, I just continued trying to vote like that and I was wondering why it wouldn't work. I tried changing all of the ports to 8000 on the servers in case they needed to match up. It didn't work. Then I realized that I also needed to change something at the bottom of all of the config files to make it work. I did exactly that. I changed the word "none" directly to "pluginMessaging" and I restarted and it still didn't function. On one particular server, I even changed the IP in the config to the IP of my Bungee server, since they are all different IPs. After a quick restart, I tested voting. Here's where things start to get interesting. Shortly after I submitted a vote, the console sent three errors:
http://pastebin.com/imHEWdBP
http://pastebin.com/yV7cgL1P
http://pastebin.com/RF8yE4fW
A few seconds after this happened, the server timed out, without me being able to log back in. This is not a usual occurrence. On the next restart, there was a Votifier error on Bungee, which was interesting considering that I had not changed the configuration between last restart and this one. Here is that error:
http://pastebin.com/1WTqkrVN

Please help ASAP. I would like to resolve this issue so I can get voting functioning and fix any underlying issues.

**Comment by Ichbinjoe** [comment]
From what it looks like, these are errors with the Java only being Java 7. I'm not sure if @tux did anything with converting to 7, but if I don't see anything tomorrow I'll commit a Java 7 friendly version.

**Comment by minecrafter** [comment]
I did forget to downgrade it to a Java 7-compatible version. On it now.

**Comment by TheMattVid** [comment]
Wow, those are some crazily fast responses! Thanks!

Once this error is cleared up, I will still need to figure out precisely how to configure my config files to make this work. Since I needed to change the Bungee port to 8000, will I need to change the ports in the other config files to 8000 as well? By default, the IP in the config files of the servers were the same IP as the individual servers themselves. Should I change those IPs to that of the Bungee occurrence, or should that remain default?

**Comment by minecrafter** [comment]
No. If you are configuring the Bukkit instances to accept forwarded votes only, you should just set `enableExternal: true`.

**Comment by Ichbinjoe** [comment]
Wait, if the instances are only taking pluginMessages as forwarding, shouldn't enableExternal be false? Or did something change I forgot about.

**Comment by minecrafter** [comment]
@Ichbinjoe I derped. It's almost 1AM here :P

**Comment by Ichbinjoe** [comment]
Ah :P but yeah @TheMatVid it should be set to false, not true. It will disable the port on the bukkit server from reviewing votes from websites. It will only take the forwarded votes from the bungee over plugin messages.

**Comment by TheMattVid** [comment]
That makes a lot of sense. Thanks! Are the IPs and ports of forwarded servers irrelevant?

**Comment by minecrafter** [comment]
Correct.

**Comment by TheMattVid** [comment]
Thank you.

**Comment by TheMattVid** [comment]
No rush, but any estimate on which day this week the compatible version may be released?
