### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by xxyy** [NuVotifier/NuVotifier#20]
The Maven repository http://repo.minimum.io/content/repositories/releases/, as declared in the [root pom of this project](https://github.com/NuVotifier/NuVotifier/blob/master/pom.xml#L34), seems to [be down](http://isup.me/repo.minimum.io). Is there a mirror available?

**Comment by minecrafter** [comment]
I might consider starting another repository, but it's fairly costly (in terms of memory/CPU usage) to run one. I'm probably going to focus on [Package Savant](https://github.com/minecrafter/package-savant) first.

**Comment by BlackCoyote** [comment]
I'll casually leave a comment here in the hopes to be notified when a maven repo exists for this plugin

**Comment by minecrafter** [comment]
@BlackCoyote You can subscribe to a GitHub issue. Look on the sidebar.

**Comment by Bammerbom** [comment]
Also really need a maven repo for this plugin
Seems like a must-havo for a plugin which provides an api like this

**Comment by PugaBear** [comment]
https://github.com/lucko/NuVotifier/commit/db2293970e088f2107fd75fe078f07b49e0f379e ? (haven't tested myself)

**Comment by Bammerbom** [comment]
Can't get it working myself, it just ignores the jar. But I am far from an expert of gradle/maven so I might be doing something wrong.
Using:
```
repositoeries {
    maven {
        name 'lucko'
        url 'https://nexus.lucko.me/repository/maven-releases/'
    }
}
dependencies {
    compile "com.vexsoftware:nuvotifier:2.3.3"
}
```

**Comment by minecrafter** [comment]
I've relented.

https://dl.bintray.com/nuvotifier/maven/

The artifact you're looking for is `com.vexsoftware:nuvotifier-universal`.

**Comment by Bammerbom** [comment]
Works, thanks!
