### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SharkZekrom** [NuVotifier/NuVotifier#203]
Hello i have this bug

>.... [16:27:24 WARN]: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 59
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at net.minecraft.server.v1_14_R1.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
>.... [16:27:24 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
>.... [16:27:24 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
>.... [16:27:24 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
>.... [16:27:24 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
>.... [16:27:24 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [16:27:24 WARN]: Caused by: java.io.IOException: Bad packet id 59
>.... [16:27:24 WARN]: at net.minecraft.server.v1_14_R1.PacketDecoder.decode(SourceFile:37)
>.... [16:27:24 WARN]: at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
>.... [16:27:24 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [16:27:24 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [16:27:24 WARN]: at us.myles.ViaVersion.util.PipelineUtil.callDecode(PipelineUtil.java:53)
>.... [16:27:24 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:40)
>.... [16:27:24 WARN]: at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
>.... [16:27:24 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [16:27:24 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [16:27:24 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:514)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
>.... [16:27:24 WARN]: ... 32 more
>.... [16:27:24 WARN]: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 59
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at net.minecraft.server.v1_14_R1.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [16:27:24 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [16:27:24 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [16:27:24 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
>.... [16:27:24 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
>.... [16:27:24 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
>.... [16:27:24 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
>.... [16:27:24 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
>.... [16:27:24 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [16:27:24 WARN]: Caused by: java.io.IOException: Bad packet id 59
>.... [16:27:24 WARN]: at net.minecraft.server.v1_14_R1.PacketDecoder.decode(SourceFile:37)
>.... [16:27:24 WARN]: at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
>.... [16:27:24 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [16:27:24 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [16:27:24 WARN]: at us.myles.ViaVersion.util.PipelineUtil.callDecode(PipelineUtil.java:53)
>.... [16:27:24 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:40)
>.... [16:27:24 WARN]: at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
>.... [16:27:24 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [16:27:24 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [16:27:24 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:514)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
>.... [16:27:24 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
>.... [16:27:24 WARN]: ... 32 more

**Comment by astei** [comment]
Not a NuVotifier bug
