### ISSUE TITLE
Some pages do not give votes to users and the keys are correct

### ISSUE THREAD

**Issue by ToxicPeople** [NuVotifier/NuVotifier#204]
### Information

**Platform on which you run NuVotifier**: 
Paper version git-Paper-110 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
**Version of NuVotifier**: 
nuvotifier 2.7.1
```
<!--
Getting this depends on your platform:

Bukkit: Use /version Votifier

Sponge: Use /sponge plugins and find NuVotifier

BungeeCord: No such command exists.

Velocity: Use /velocity plugins from in-game and hover over "nuvotifier"
-->
```

**Relevant log**: 
### Details

**Description**  

Users usually vote on 5 pages, of which only 2 are giving them rewards. Which even seems strange to me. This happens since I set up a firewall, I don't know if it will have to.
**Steps to reproduce**  

I think it was through the firewall but I'm not sure
**Expected behavior**  

I hoped that users could receive their votes properly, but currently only 2 pages give them rewards

**Comment by astei** [comment]
Please go through the [troubleshooting guide](https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide), it seems you made a mistake while setting up the firewall (or you misconfigured the other sites).
