### ISSUE TITLE
How can I figure out the IPs of the Vote websites that Im sending votes from?

### ISSUE THREAD

**Issue by TomLewis** [NuVotifier/NuVotifier#210]
Hosting for 8 years, first time having my bungee attacked because the query feature is vulnerable and will take down a bungee.
The solution i've been told, is to setup a firewall to just allow UDP packets from trusted sources, how on earth do I track which services/vote websites IPs are being used to check port 25565 on UDP for querying the minecraft server using query?

**Comment by astei** [comment]
You're in the wrong place to ask this question. This question has nothing to do with NuVotifier.

**Comment by TomLewis** [comment]
> You're in the wrong place to ask this question. This question has nothing to do with NuVotifier.

Apart from:

1. Its everything to do with vote websites
2. NuVotifier does not log the IP's of the vote website servers
3. You need to know the IP's of vote websites to setup a firewall rule to stop known attacks, this is known by the Spigot & Paper devs, the CORE plugin required to talk to Vote websites is NuVotifier, this is exactly the place this should be answered.

Alternatively, Log the IPS and save everyone a headache.

**Comment by mikroskeem** [comment]
> just allow UDP packets from trusted sources
> this is exactly the place this should be answered.

Wait... (Nu)Votifier has nothing to do with UDP query, also known as GS4 Query. Why are you here?

> You need to know the IP's of vote websites

Might as well ask vote sites? I'm pretty sure they're willing to provide their list of IP addresses. For example Minecraft-MP:
![image](https://user-images.githubusercontent.com/3490861/92948627-52b83e00-f462-11ea-9927-e3b268f1ef9e.png)

**Comment by Ichbinjoe** [comment]
This question definitely sounds like its about GS4, not the Votifier protocol or NuVotifier. While server lists may implement GS4, NuVotifier has absolutely _nothing_ to do with it (these are instead implemented within the servers themselves).

As this is not a bug or feature request (yet OP feels it is), I'm locking discussion.
