### ISSUE TITLE
Votes getting cached for 1 backend server but not for another.

### ISSUE THREAD

**Issue by BlitzGamer-88** [NuVotifier/NuVotifier#214]
NuVotifier versions:
- bungee: 2.7.1
- survival: 2.7.1
- oneblock: 2.7.1

Config files:
- bungee: https://paste.helpch.at/yufocewoja.bash
- survival: https://paste.helpch.at/uyileloniy.makefile
- oneblock: https://paste.helpch.at/evuxateraq.makefile

Of course the tokens are correctly set I just deleted them.

Server versions:
- bungee: bungee-dev-build-1539
- survival: git-Paper-133 (MC: 1.16.1)
- oneblock: git-Paper-133 (MC: 1.16.1)

**Description**  
So when someone votes, the votes is seen by the proxy nuvotifier as seen here: https://paste.helpch.at/eselobipoy.cs and sent to the other servers. The problem is I've set in config for the vote to be cached if the player is not online. It does that for the oneblock server but for the survival server it sends the vote right away. So if the player is not online on survival when he votes, he doesn't get the vote rewards anymore since by the time he joined, the vote is already sent. On oneblock, it gets cached correctly tho.

I have to also mention that I have a dedicated server that's why I configured the plugin the way it is.

**Expected behavior**  
I expected the votes to get cached on both backend servers.

Thank you for your time.

**Comment by astei** [comment]
This report doesn't make sense. That log would only be output if you had the plugin not forwarding votes immediately for offline players. I would suggest restarting the server in this case.
