### ISSUE TITLE
I can't tell what is the issue with votifier

### ISSUE THREAD

**Issue by Troaxx** [NuVotifier/NuVotifier#215]
I believe my votifier is not listening to votes, but I configured it properly. I tried using another additional port (provided by hosting, I've tried 2 ports provided by them, and typed a random one. They all bind according to votifier.) from the one I previously used, redownloading the votifier plugin, changed host from 0.0.0.0 to server IP (and back to 0.0.0.0) and sending test votes with votifier tester also works. I can't tell what's wrong with my votifier. Nothing pops up on my console when I send test votes or vote on the actual site. There is an issue with the 'service site' on votingplugin, but I'm assuming votingplugin is okay and votifier is the issue here. In console logs, votifier was enabled, then disabled with no reason why. 
https://paste.shockbyte.com/ifijehuduvayuruxapal

EDIT: definitely is votifier problem, tested with minecraftservers.org https://prnt.sc/vnmyc1

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide
