### ISSUE TITLE
Unable to process vote

### ISSUE THREAD

**Issue by TadiklCZE** [NuVotifier/NuVotifier#218]
Hey! I just looked into my console and it sent this error from any reason.

I use nuvotifier 2.7.1 and waterfall.

![image](https://user-images.githubusercontent.com/48769171/100420532-e8895f80-3086-11eb-9068-107cb552b901.png)

**Comment by Ichbinjoe** [comment]
Literally looks like normal TCP traffic behavior. This is likely just internet scanning, as the ip belongs to 'zservers.ru'. https://zservers.ru
