### ISSUE TITLE
Relocate conflicting shaded library

### ISSUE THREAD

**Issue by crashdemons** [NuVotifier/NuVotifier#223]
Hello, we're currently discussing the cause of a recent GSON exception on multiple servers (ref https://hub.spigotmc.org/jira/browse/SPIGOT-6056 )

while checking jars for conflicting namespaces, I noticed that NuVotifier shades in a library that is shared by other plugins
because they are shaded in at the same namespace,
this could cause conflicts and exceptions if there are version differences - so it's preferred that shaded libraries are 'relocated' to a plugin namespace (like com.google.gson -> nuvotifier.com.google.gson)...

Anyway I thought I would bring this up and make the suggestion, feel free to ignore me if this is misinformed.

**Comment by astei** [comment]
Already fixed with #221

**Comment by crashdemons** [comment]
apologies, I was checking the released version in this case. I will try to rebuild from source.
