### ISSUE TITLE
Rsa keys

### ISSUE THREAD

**Issue by jwavey** [NuVotifier/NuVotifier#224]
Hello i was transferred to a different server node and votifier wont connect to any sites now, my rsa keys are the exact same every time. ive deleted all files and reinstalled, tried everything but just get same rsa key everytime?

**Comment by jwavey** [comment]
& dont close cos this is not a setup issue, i had it working fine but now it wont work, dont say not doing it properly cos all it is deleteing files and re installing

**Comment by jwavey** [comment]
it is a bug generating some key everytime

**Comment by jwavey** [comment]
Votifier was not able to bind to /54.36.227.235:8317

**Comment by astei** [comment]
You’ll need to fix your bind configuration due to the node switch, swap out the IP for the new one in your server.properties

Also this is literally a setup issue so I’m closing this

**Comment by jwavey** [comment]
It is not possible for me to change ip in server.properties there is no option

**Comment by jwavey** [comment]
i have change the ip in properties, and same problem
