### ISSUE TITLE
why close it... it will take you 2 mins to help me????

### ISSUE THREAD

**Issue by jwavey** [NuVotifier/NuVotifier#225]
I have changed the ip is system properties and it has made no difference, if you dont help i wont be able to use votifier again cos it wont work at all. you say this sis a setup problem, no its not i have sent it it up before its so easy? so why wont it connect to this time just cant bind to my ip. No one has any idea what is causing this

**Comment by jwavey** [comment]
31.01 10:23:09 [Server] INFO Reloading NuVotifier...
31.01 10:23:09 [Server] INFO Loaded token for website: default
31.01 10:23:09 [Server] INFO Using epoll transport to accept votes.
31.01 10:23:09 [Server] INFO Method none selected for vote forwarding: Votes will not be received from a forwarder.
31.01 10:23:09 [Server] INFO Reload was successful.
31.01 10:23:09 [Server] INFO NuVotifier has been reloaded!
31.01 10:23:09 [Server] INFO Votifier enabled on socket /0:0:0:0:0:0:0:0%0:8317.


like if i set ip to my server ip there^^ it says cant bind

**Comment by astei** [comment]
Final warning. We do not provide support for setting up the plugin.

That log snippet suggests NuVotifier is working but you put in the wrong IP on your voting site. Closing this again.

**Comment by jwavey** [comment]
ah whatever mate, thanks alot for being so helpfull
