### ISSUE TITLE
Bungee Console error

### ISSUE THREAD

**Issue by LuluxClient** [NuVotifier/NuVotifier#232]
### Information

**Platform on which you run NuVotifier**: 
BungeeCord
**Version of NuVotifier**: 
2.7.2
```
<!--
Getting this depends on your platform:

Bukkit: Use /version Votifier

Sponge: Use /sponge plugins and find NuVotifier

BungeeCord: No such command exists.

Velocity: Use /velocity plugins from in-game and hover over "nuvotifier"
-->
```

**Relevant log**: 
### Details
https://pastebin.com/XygB0nv3
**Description**  

When someone is trying to vote on a website
**Steps to reproduce**  

Just go on our voting website and vote and bam, error
**Expected behavior**  

```
Please make sure to delete this line of text and the three ``` characters surrounding it, or your issue will be closed.
```

**Comment by Ichbinjoe** [comment]
misconfiguration. https://github.com/NuVotifier/NuVotifier/wiki/Setup-Guide
