### ISSUE TITLE
Unable to resolve nuvotifier during compile

### ISSUE THREAD

**Issue by dkbay** [NuVotifier/NuVotifier#234]
### Information

**Platform on which you run NuVotifier**: 

**Version of NuVotifier**: 2.7.2

**Relevant log**: ![image](https://user-images.githubusercontent.com/1548975/116117788-ecb0bc00-a6bc-11eb-8abb-b695e5d420c5.png)
### Details

**Description**  
When my Github action runs the build process it seems to fail on nuvotifier every time though it worked a day ago and I haven't changed anything related to nuvotifier or the maven file.

Edit: After asking on some Discords this seems to be due to Bintray being sunset so maybe we can get an update on the wiki with a new repo?

**Steps to reproduce**  
I don't know if I can provide these. I just try to build a plugin that requires votifier and it fails.

**Expected behavior**  
That it builds without failing to resolve stuff.

**Comment by Ichbinjoe** [comment]
Hrm okay give me a day or two. Rip bintray

**Comment by dkbay** [comment]
Thanks! :D

Also I'm sorry if my issue isn't the best, I don't make a lot of issues on open source stuff. 👀

**Comment by Pugabyte** [comment]
This is now affecting my team too, looking forward to a fix

**Comment by Ichbinjoe** [comment]
@Pugabyte if you are blocked, host it on your own repository. This isn't my job, and I have higher priority things on my plate right now.

**Comment by dkbay** [comment]
@HexedHero & @Pugabyte I don't think it's reasonable that you guys give him a thumbs down.

He's working on and maintaining this plugin for all of us, free of charge out of the goodness of his heart.
I think it's unreasonable to demand he fix something from one day to the next.

Have some patience or set up a workaround.

**Comment by Ichbinjoe** [comment]
See #237
