### ISSUE TITLE
I vote but nothing happens

### ISSUE THREAD

**Issue by Malay1121** [NuVotifier/NuVotifier#236]
I have added correct ip host and port still when I vote, nothing happens, please check the images above. Please tell me the reason behind this and it's solution. 
![adsdad](https://user-images.githubusercontent.com/56907997/117793029-776eea80-b269-11eb-9b5f-06b045275da7.PNG)

![asdy](https://user-images.githubusercontent.com/56907997/117793476-e2b8bc80-b269-11eb-9af5-cc846545619e.PNG)
![asdds](https://user-images.githubusercontent.com/56907997/117793708-1bf12c80-b26a-11eb-8600-fd87d7178103.PNG)

**Comment by Ichbinjoe** [comment]
Your votifier port is not your Minecraft port. Use a different port.
