### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by KolakZ** [NuVotifier/NuVotifier#244]
1. NuVotifier 2.7.2

2. [2021-05-22-3.log.gz](https://github.com/NuVotifier/NuVotifier/files/6525533/2021-05-22-3.log.gz)
https://gist.github.com/KolakZ/58df4d2f835a03f86f33532bb52107e5

3. Bungeecord, but this config and log is on a bukkit server

**Relevant log**: https://gist.github.com/KolakZ/3b966078d908ed8b53651eac98bdd244

**Description**  
I get the following error on server shutdown and am not sure what it means: https://gist.github.com/KolakZ/3b966078d908ed8b53651eac98bdd244

**Comment by Ichbinjoe** [comment]
#241
