### ISSUE TITLE
Exception in thread "Votifier NIO boss" java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by viveleroi** [NuVotifier/NuVotifier#246]
### Information

**Platform on which you run NuVotifier**: Paper 1.16.5 build 714

**Version of NuVotifier**: 2.7.2

**Relevant log**: https://paste.gg/p/anonymous/20bc6bb60fa64984b400668e46a5d67a

### Details

**Description**  
This error appears on shutdown when using builds of paper. It did not happen on paper build 674, but does with 714, so it broke sometime between.

**Steps to reproduce**  
Use paper build 714, run a server, then shutdown.

**Expected behavior**  
No error

**Comment by astei** [comment]
Issue was fixed in 669c8a769e. The parent issue #241 was already fixed minutes ago.
