### ISSUE TITLE
An at least 1/4 million downloads king of the vote rewarder hill has fallen. Maybe you can help?

### ISSUE THREAD

**Issue by Coldene** [NuVotifier/NuVotifier#255]
Hi. Is there any chance NuVotifier 2.7.2 is no longer talking right with GAListener?
It worked fine till 1.16+ GAListener plugin has around 1/4 million downloads on bukkit and 
I expect many elsewhere also. Just 66kb. Zero lag. Was awesome.
Someone made GAListener 1.4.0 and that worked all way up to 1.15.
I now start a 1.16.5 server and GAListener does everything as usual except 
actually run the commands for votes recieved. /DOH!!! There is no console error.

Pretty sure you know how much sense it would make if you, NuVotifier dev, also 
released a vote reward plugin that works with yours? GAListener 2?
VotingPlugin is a massive behemoth of configs and optioins, a bit laggy too. 1.8mb
GAListener does loads of vote handling reward tricks and is just 66kb.
Take a peek? https://github.com/Raxdiam/GAListener/releases/tag/1.4.0
Open sourec for years. Voting Plugin is simply toooooo big and laggy.
There is a huge demand for a smaller vote reward plugin. So says 
the Voting Plugin dev who is "thinking" about making a lite version of his.

Save us!? Also I expect you would get alot of love and downloads 
in the 100s of 1000s over time for GAListener 2 if you released it.
Is only 66kb and likely just a few kb needs edited to get it to work?
Be the hero... Pop that source and have a look? I no know Java...
I thank you for your time and consideration regarding possibly 
saving this once majestic king of the vote rewards plugin hill.

Nothing wrong with my config either.
https://pastebin.com/8vb9KW3H

**Comment by astei** [comment]
We're not interested, sorry.
