### ISSUE TITLE
1.17 spigot with nuvotifier # 35

### ISSUE THREAD

**Issue by comonier** [NuVotifier/NuVotifier#259]
[error](https://hastebin.com/afizozunay.properties)

**Comment by astei** [comment]
Read the wiki

**Comment by comonier** [comment]
CorruptedFrameExceptions
If you get this, somebody sent malformed data to NuVotifier. Typically, there is a descriptive message (such as telling you the public key is wrong). There are also some sanity checks to ensure clients follow the protocol, which show up as messages without any clear resolution. There is nothing you can do, this is just the unfortunate nature of the internet.

if the plublic key was not correct, the test on the planet minecraft website which only allows adding the votifier settings after testing the connection, would not allow me to save the information on the website you can check if you want

https://www.planetminecraft.com/

**Comment by comonier** [comment]
well but i solve it in other way:

the problem was - i dont know why votifier change all files after update to 1.17
so i get backup files and replace [public.key]
But i check also the config.yml was change so i re-edited it with the right door.

problem still...

so i check again e i found the token was changed also, so i get backup line of token and replace it also..

now it works... ty for NOTHING cause i solve it alone.
