### ISSUE TITLE
Exception on plugin disable

### ISSUE THREAD

**Issue by TheosisOfficial** [NuVotifier/NuVotifier#271]
### Information

**Platform on which you run NuVotifier**: Bukkit

**Version of NuVotifier**: 2.7.3

**Relevant log**: https://gist.github.com/TheosisOfficial/22a5ba529495b6842885d1f7052bd8ab
### Details

**Description**  
I haven't noticed anything besides this exception. I haven't touched any configuration, it's all default.

**Steps to reproduce**  
1. Install NuVotifier
2. Start your server
3. Stop your server

**Expected behavior**  
The exception not to occur.

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#why-do-i-get-javalangillegalstateexception-zip-file-closed-when-i-shutdown-the-server
