### ISSUE TITLE
Votifier Listener bug

### ISSUE THREAD

**Issue by MasonKidder345** [NuVotifier/NuVotifier#273]
### Information

**Platform on which you run NuVotifier**:  Bukkit 
**Version of NuVotifier**: 2.7.3

**Relevant log**: https://gist.github.com/MasonKidder345/abb6d313c7391c628591518e0cb699e1 
### Details

**Description**  I get votes and everything works perfectly fine I just get it whenever I restart the server like while it disables the plugin and its not always 100% on restart like it sometimes may not happen but on other times it may happen.  

**Steps to reproduce**  
Happens randomly whenever I restart the sever 

**Expected behavior**

**Comment by astei** [comment]
https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#why-do-i-get-javalangillegalstateexception-zip-file-closed-when-i-shutdown-the-server
