### ISSUE TITLE
WIKI - Add zVoteParty plugin

### ISSUE THREAD

**Issue by Maxlego08** [NuVotifier/NuVotifier#274]
Hello,

Can you add the zVotifier plugin in the list of plugins that use NuVotifier?

Link to spigot: [https://www.spigotmc.org/resources/zvoteparty-voting-plugin.95603/](https://www.spigotmc.org/resources/zvoteparty-voting-plugin.95603/)
Link to GroupZ: [https://groupez.dev/resources/zvoteparty.124](https://groupez.dev/resources/zvoteparty.124)

**Comment by astei** [comment]
No
