### ISSUE TITLE
PocketVote compability

### ISSUE THREAD

**Issue by BijuuKrunos** [NuVotifier/NuVotifier#275]
Heyho,

I wanted to know if you could provide support for Pocketvote:
https://github.com/ProjectInfinity/PocketVote

This is a Voting listener and website used for Bedrock Edition Servers.
Thx to Geyser you can have crossplay now and there will be more and more crossplay Servers rising like mine, for that it would be cool if NuVotifier could support that.

Have a nice day.

Kind Regards,
Krunos

**Comment by astei** [comment]
It would be trivial to write a plugin that implements this API, but it's not something we wish to do (inducing a dependency on an external service).

Closing.
