### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by russianpeanut** [NuVotifier/NuVotifier#276]
### Information

Bungeecord

**Version of NuVotifier**: 
2.7.3

**Relevant log**: https://gist.github.com/russianpeanut/1c5f132749f2c090da343ec7c1107e8c
### Details

**Description**  
So i get this error, and the config is correct, i use secondary port everything is correct. I dont know why is it saying that the IP is wrong the voting works but it sometimes crashes the server :/

**Steps to reproduce**  
I dont know, it just once appeared maybe it caused because i added another server

**Expected behavior**  
To not crash my server

Also here is my config for bungee and for the spigot server that crashes

https://gist.github.com/russianpeanut/6638252684fe5ed7107f2b4b9cd697b8 - bungee
https://gist.github.com/russianpeanut/d332bd02504a51fa75b54a343e62723f - spigot

I see nothing wrong in config, that why i am reporting it as i bug

**Comment by russianpeanut** [comment]
please respond

**Comment by astei** [comment]
I would suggest resetting your keys. As for this error, proxy vote forwarding is not a recommended setup and you're probably better off with plugin messaging.
