### ISSUE TITLE
Event Doesn't Fire on 1.17 BungeeCord

### ISSUE THREAD

**Issue by jiajunmao** [NuVotifier/NuVotifier#277]
I am opening this issue again because similar things are observed on 1.17 bungee. The VoteEvent seems to not fire when NuVotifer prints vote received in console. The code used to listen for the event is as follows

```java
public class VotifierListener implements Listener {

    @EventHandler
    public void onVote(VotifierEvent e) {
        ProxyServer.getInstance().getConsole().sendMessage("A vote received for " + e.getVote().getUsername() + " at time " + e.getVote().getTimeStamp());
    }
}
```

_Originally posted by @jiajunmao in https://github.com/NuVotifier/NuVotifier/issues/53#issuecomment-913192318_

**Comment by jiajunmao** [comment]
Reference to #53

**Comment by astei** [comment]
This issue is unrelated to #53 and is most likely you not registering your listener correctly.
