### ISSUE TITLE
onlySendToJoinedServer option not working?

### ISSUE THREAD

**Issue by LazosPlaying** [NuVotifier/NuVotifier#28]
Hello i am having an issue where the "onlySendToJoinedServer" option does not work (even tho it is enabled) and the votes are forwarded to all subservers.

Any clue why would that happen, what could i mess up?

Thank you in advance.

**Comment by Hodel1** [comment]
Yes, the vote will be forwarded to any servers. But only rewards the user, where he is online.
We had the same issue, that the user was rewarded on every server after every vote - but that was a config problem on the votelistener plugin.

**Comment by LazosPlaying** [comment]
Well, first of all sorry for no closing the issue.

Second of all, for people that might be searching for help on this topic, the issue was "forwarding method" in order to run "onlySendToJoinedServer" you need to be using "PluginMessaging" option.
