### ISSUE TITLE
Problem with votifier port

### ISSUE THREAD

**Issue by ReneRuts** [NuVotifier/NuVotifier#280]
When I try to add the votifier port to a voteing site it says this 

Unable to connect to the Votifier server on Port: 8192 - Are you sure you have Votifier installed?

but i checked the port 20 times and it is that port but it keeps giving that error and i don't know how to solve it and why it gives that error altough i could use that port at other sites.

**Comment by astei** [comment]
I would double check if you have entered your IP correctly, that your public key is correct, and that the voting site isn't being blocked by your firewall. If you continue to have difficulties, contact the owner of the server list.
