### ISSUE TITLE
Purging out of date vote

### ISSUE THREAD

**Issue by Skjolberg** [NuVotifier/NuVotifier#282]
### Information

**Platform on which you run NuVotifier**: Waterfall

**Version of NuVotifier**: Last, 2.7.3, W

```
<!--
Getting this depends on your platform:

Bukkit: Use /version Votifier

Sponge: Use /sponge plugins and find NuVotifier

BungeeCord: No such command exists.

Velocity: Use /velocity plugins from in-game and hover over "nuvotifier"
-->
```

**Relevant log**: https://gist.github.com/Skjolberg/857580b1dcfb25a08208568f9220a875
### Details

**Description**  
It always appears at all hours.

**Steps to reproduce**  

**Expected behavior**

**Comment by Ichbinjoe** [comment]
Working as intended?
