### ISSUE TITLE
How to make 3rd party plugin through nuvotifier

### ISSUE THREAD

**Issue by NCSV** [NuVotifier/NuVotifier#293]
### Information

**Platform on which you run NuVotifier**: 

**Version of NuVotifier**: 

```
<!--
Getting this depends on your platform:

Bukkit: Use /version Votifier

Sponge: Use /sponge plugins and find NuVotifier

BungeeCord: No such command exists.

Velocity: Use /velocity plugins from in-game and hover over "nuvotifier"
-->
```

**Relevant log**: 
### Details

**Description**  
now i making vote listener plugin.
i followed this step (https://jitpack.io/p/NuVotifier/NuVotifier), but when server loaded,
this error was occur. (Ambiguous plugin name `Votifier' for files `plugins\nuvotifier.jar' and `plugins\EcseVote-1.0-SNAPSHOT.jar' in `plugins')
i also set softdepend in plugin.yml, changed class name.

**Comment by JOO200** [comment]
Don't set the name of your plugin to Votifier, use some other name. To depend on NuVotifier set the soft-depend to Votifier
