### ISSUE TITLE
Adding to server list.

### ISSUE THREAD

**Issue by ItzHayno** [NuVotifier/NuVotifier#30]
How do I add this to my server list?

Also, does it support sending votes to votifier?

P.S. I have checked the javascript protocol but I didn't understand it.

**Comment by EmanYm** [comment]
There is [a wiki](https://github.com/NuVotifier/NuVotifier/blob/master/usage.md)

**Comment by ItzHayno** [comment]
Yes but I need this to work on servers with the original Votifier plugin.

**Comment by yepidoodles** [comment]
@ItzHayno NuVotifier is a replacement for the original Votifier plugin.

**Comment by EmanYm** [comment]
> Is NuVotifier a drop-in replacement for Votifier?

It says this in the readme.md, the first page that is displayed when you come to the Github.
