### ISSUE TITLE
Change Maven import in wiki

### ISSUE THREAD

**Issue by zax71** [NuVotifier/NuVotifier#305]
Change [https://github.com/NuVotifier/NuVotifier/wiki/Developer-Documentation#maven](https://github.com/NuVotifier/NuVotifier/wiki/Developer-Documentation#maven) to say 
```html
<dependency>
  <groupId>com.github.NuVotifier</groupId>
  <artifactId>NuVotifier</artifactId>
  <version>2.7.2</version>
  <scope>provided</scope>
</dependency>
```
Will save others the hours it took me to find that

**Comment by JOO200** [comment]
Duplicate of https://github.com/NuVotifier/NuVotifier/issues/286
Not sure why you're creating another issue for that

**Comment by zax71** [comment]
Wow I forgot about that xD I just ran in to this again and saw the wiki wasn’t editable

**Comment by baileyqdotme** [comment]
tysm even though this is a year old i kept trying to figure out why my listener was not working. honestly thank you so much!!
