### ISSUE TITLE
Bad packets

### ISSUE THREAD

**Issue by Skyw0lf07** [NuVotifier/NuVotifier#311]
I'm getting this error when someone votes and I don't know how to solve it. I'm using Bungeecord (flamecord) and I have no mods. Only plugins.
![IMG_20221121_182256](https://user-images.githubusercontent.com/81262586/203131771-a5845251-23bc-4e86-bfbd-404e5aa5eb56.jpg)

**Comment by JOO200** [comment]
That's not a log message from NuVotifier.
Make sure to not use the same port for NuVotifier and BungeeCord/Minecraft Servers.

**Comment by astei** [comment]
not from NuVotifier
