### ISSUE TITLE
issue with setting up for Bungee network

### ISSUE THREAD

**Issue by DisguisedTurtlee** [NuVotifier/NuVotifier#312]
So I have watched SoulStriker tutorial on setting up NuVotifier for Bungee networks and I did the same as he did. The proxy server is getting the test votes I send but it can't send these votes to the other servers and here is a pic of the error
![image](https://user-images.githubusercontent.com/98926056/204421571-af7f211c-0134-4e9f-8842-52666a3a3017.png)

**Comment by BlackRandomCraft** [comment]
pterodactyl?

**Comment by DisguisedTurtlee** [comment]
yep

**Comment by BlackRandomCraft** [comment]
I understand you used the guide https://pterodactyl.io/community/games/minecraft.html but you use 172.0.0.1 instead of 172.18.0.1. try 172.18.0.1 instead of 127.0.0.1

**Comment by BlackRandomCraft** [comment]
and also make sure that you open ports with the command

ufw allow in on pterodactyl0 to 172.18.0.1 port <LOCALHOST_PORT> proto tcp

**Comment by DisguisedTurtlee** [comment]
Thank you so much homie it's working fine now!

**Comment by JosTheDude** [comment]
@astei Requesting this issue be closed c:
