### ISSUE TITLE
Console error on startup

### ISSUE THREAD

**Issue by zThana** [NuVotifier/NuVotifier#318]
### Information

**Platform on which you run NuVotifier**: Arclight
**Version of NuVotifier**: 2.7.3
**Relevant log**: https://gist.github.com/zThana/c9b8c6dc73431e04266ee03eb5d07ba6

### Details

**Description**  
Simply happens on startup. Plugin still works, although I noticed this while going through the debug log.

**Steps to reproduce**  
No idea.

**Expected behavior**  
The error to not show up.

**Comment by astei** [comment]
not an error, just "Arclight" spewing debug output from Netty
