### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by M1SM4TCH** [NuVotifier/NuVotifier#32]
https://pastebin.com/cMC1VhSj

It happens when I turn off the server.
Do not know why of error, it influences something?

**Comment by Ichbinjoe** [comment]
Appears related to netty versioning ... i bumped the version and cleaned up some tests which were dumping similarly... hopefully that fixes it.

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/releases/tag/v2.3.6-pre

Please try this version. Reopen this issue if you are still having issues.
