### ISSUE TITLE
nah

### ISSUE THREAD

**Issue by ghost** [NuVotifier/NuVotifier#335]
nah

**Comment by CloudeLecaw** [comment]
You need to use Version 3.0.0. for that.

https://github.com/NuVotifier/NuVotifier/issues/323

**Comment by Nunchakin** [comment]
> You need to use Version 3.0.0. for that.
> 
> #323

Thanks for trying to help, but it still doesn't forward it on 1.21

**Comment by CloudeLecaw** [comment]
> > You need to use Version 3.0.0. for that.
> > #323
> 
> Thanks for trying to help, but the version still doesn't forward it on 1.21

why not? we also use this version on paper 1.21 and the players recive the rewards.  we use the v1 one..

**Comment by Tunikaso** [comment]
where can I download version 3.0.0? I can't find it anywhere.

**Comment by CloudeLecaw** [comment]
i linked in allready twice in #323

may you noticed Nuvotifer isnt developed anymore so the dev servers are down.
so take the file from this thread :-)

**Comment by CloudeLecaw** [comment]
> where can I download version 3.0.0? I can't find it anywhere.

i linked in allready twice here. you find it in thread #323

may you noticed Nuvotifer isnt developed anymore and the dev servers are down.
so take the file from this thread :-)
