### ISSUE TITLE
Maven does not have 2.3.5

### ISSUE THREAD

**Issue by Deanveloper** [NuVotifier/NuVotifier#34]
In a previous issue https://github.com/NuVotifier/NuVotifier/issues/20, it was stated that the repo for NuVotifier is https://dl.bintray.com/nuvotifier/maven/

On that repo, the only version is 2.3.4, as seen here: https://dl.bintray.com/nuvotifier/maven/com/vexsoftware/

**Comment by Ichbinjoe** [comment]
I do not have access to the bintray. However, I will state the following:

This plugin is API compatible with the original votifier (for the most part). Where it is not, 2.3.5 on is compatible with 2.3.4 - unless you are static linking the plugin (shading/shadowing) for whatever reason, depending on 2.3.4 is perfectly fine. Reopen if you have a usecase for needing 2.3.5 in a repository.

**Comment by ImranDoet** [comment]
Thanks
