### ISSUE TITLE
Unable to send vote to /127.0.0.1:8193. This vote will be lost!

### ISSUE THREAD

**Issue by UnrealPixel** [NuVotifier/NuVotifier#37]
Error: https://hastebin.com/asirasalam.md

Idk what to do???

**Comment by LoXR** [comment]
Same here, needing help. Getting [Votifier] Unable to process vote from spamming in my console. But I do believe all support has been dropped for this plugin.

**Comment by Ichbinjoe** [comment]
This issue may be fixed with new 2.3.6... Appears to be something seen with Netty.

**Comment by Ichbinjoe** [comment]
https://github.com/NuVotifier/NuVotifier/releases/tag/v2.3.6-pre

Please try this version. Reopen this issue if you are still having issues.
