### ISSUE TITLE
Not registering Votes

### ISSUE THREAD

**Issue by xAcrosonicx** [NuVotifier/NuVotifier#42]
[Archive.zip](https://github.com/NuVotifier/NuVotifier/files/1459333/Archive.zip)
I have attached both of my files for the plugins. Here is my server:
192.95.30.131:25843

**Comment by Ichbinjoe** [comment]
The port you listed to listen on is your Minecraft Server port. These should not be the same. If you looked at your log, NuVotifier would have errored out because of this. Please change your NuVotifier listening port.
