### ISSUE TITLE
Crashes - Sponge - 1.10.2

### ISSUE THREAD

**Issue by yepidoodles** [NuVotifier/NuVotifier#43]
Hello,

So last week, out of the blue, on one of my scheduled server restarts, NuVotifier started crashing my server, for no apparent reason, I hadn't changed anything for days before hand, and the crash reports are strange. I also have another server running on that machine (using a different port), which has absolutely no issues with it.

Since then I've tried updating various plugins, Sponge etc, but still crashes. Even though many of the crash reports do not even point to NuVotifier; when I remove it, they stop. Today I managed to get it to start a few times, but each time the votes would not go through.

I've tried using both v2.3.5 and v2.3.6-pre.
Minecraft: 1.10.2
SpongeForge: 1.10.2-2477-5.2.0-BETA-2731

Most relevant crash report: https://pastebin.com/GaGFu0cT

I'm happy to provide any other information you may need.

- Alice

**Comment by Ichbinjoe** [comment]
May be fixed by #36? I'm not familiar enough with sponge, but this does not look plugin related.

**Comment by yepidoodles** [comment]
Tried the re-download, and I thought #36 was 2.3.6-pre ?

**Comment by Ichbinjoe** [comment]
#36 has yet to be merged. I am waiting on the pr author to fix the issues I outlined. I am not a sponge developer and do not feel comfortable updating it myself.

**Comment by Ichbinjoe** [comment]
Fixed within 2.3.6 release
