### ISSUE TITLE
erro no votifier quando lança voto

### ISSUE THREAD

**Issue by AxlArns** [NuVotifier/NuVotifier#46]
Olá estou tendo um problema em certo sites de votação quando testo o nuvotifier dar esse erro '01.12 21:11:07 [Server] ERROR [Votifier] Unable to process vote from /50.28.37.175:58304' como posso resolver isso... versao do minecraft e 1.12.2 e do plugin nuvotifier 2.3.5

**Comment by Ichbinjoe** [comment]
Please update to 2.3.6-pre, however, I feel like this is a configuration issue.
