### ISSUE TITLE
Interesting.... Cant bind to the address....

### ISSUE THREAD

**Issue by DarkPotato23** [NuVotifier/NuVotifier#47]
It goes from bottom to top.. that's how my console is :p

02.12 09:50:09 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannel.bind(AbstractChannel.java:198) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485) [nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at com.vexsoftware.votifier.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125) ~[nuvotifier-universal-2.3.5.jar:?]
02.12 09:50:09 [Server] INFO at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[?:1.8.0_111]
02.12 09:50:09 [Server] INFO at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[?:1.8.0_111]
02.12 09:50:09 [Server] INFO at sun.nio.ch.Net.bind(Unknown Source) ~[?:1.8.0_111]
02.12 09:50:09 [Server] INFO at sun.nio.ch.Net.bind(Unknown Source) ~[?:1.8.0_111]
02.12 09:50:09 [Server] INFO at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_111]
02.12 09:50:09 [Server] INFO java.net.BindException: Address already in use
02.12 09:50:09 [Server] ERROR Votifier was not able to bind to /162.244.165.71:39526

**Comment by Ichbinjoe** [comment]
This is due to one of three situations (really one, but I feel like its better to explain all seperately):

1) You are binding to your 'Minecraft' port - NuVotifier (or the original votifier for that matter) is unable to bind to the Minecraft port
2) You are on a shared host and binding to someone else's port. This also won't work.
3) Something else is listening on that port. We need an empty port.

So, as the exception says, we can't bind to the port because something already bound to the port. We need a unique port to bind to. Please pick a new port (if you are on a shared host, talk to your host about doing this).
