### ISSUE TITLE
GAListener with NuVotifer 

### ISSUE THREAD

**Issue by NotableOsprey92** [NuVotifier/NuVotifier#5]
Ok dont know how to link GAListener with nuvotifer because with the old votifer you had a listener folder but with nu you dont and it does not say how in the config to set it up.

**Comment by Ichbinjoe** [comment]
If I am remembering correctly, GAListener does __not__ use the class based listener, and instead uses the event based listener. You should be able to use it just like normal votifier with no modifications.

**Comment by NotableOsprey92** [comment]
How because they way you would set it up with votifier was with the listener folder but with nu it does not have a folder called listeners.

Skype:notableosprey92

**Comment by Ichbinjoe** [comment]
You should have not been using the listener folder with GAListener. GAListener uses events, which this plugin supports.
