### ISSUE TITLE
Crazy high ticks from NuVotifier

### ISSUE THREAD

**Issue by Kbryst** [NuVotifier/NuVotifier#50]
Spigot 1.12.2 (NuVotifier 2.3.5)

https://imgur.com/SzBRFFZ

Not sure what else you would like provided, just let me know.

**Comment by Ichbinjoe** [comment]
I will not provide performance support from timings. Please provide a server profile. You can use https://github.com/sk89q/WarmRoast to get this easily. Usually, high CPU usage from Nuvotifier is a direct result of a listener taking too much time, and cannot be helped by NuVotifier.
