### ISSUE TITLE
[Question] Votes

### ISSUE THREAD

**Issue by SeDark** [NuVotifier/NuVotifier#52]
[nioEventLoopGroup-2-1/ERROR]: [Votifier] Unable to process vote from /47.91.196.72:64680

My question is if this error affects something, since it appears very often, changing the IP and the port.

**Comment by Ichbinjoe** [comment]
Hi SeDark,

I checked the whois on that ip, and it appears to be from an Alibaba 'ALICOLOUD' server from China. It is doubtful that this is a legitimate request, and it is safe to ignore these errors.
