### ISSUE TITLE
Event Doesn't Fire on BungeeCord Plugin With Lastest BungeeCord

### ISSUE THREAD

**Issue by mkcoldwolf** [NuVotifier/NuVotifier#53]
as The issue #27
I remeber my code work in pass prefectly and it seems started to bug after an bungee update
It would have a same Error from #27 on Debug mode
After the Error i still got this
` [NuVotifier] Got a protocol v1 vote record from /185.56.63.151:53476 -> Vote (from:SERVERPACTTEST username:MKCOLDWOLF address:xxx.xxx.xx.xxx timeStamp:1515343721)`
But my Event that made in BungeeCord PLugin Folder seems doesnt fire
Here is my code

    package mccw.bungeecore.Modules.Vote;

    import com.vexsoftware.votifier.bungee.events.VotifierEvent;
    import com.vexsoftware.votifier.model.Vote;

    import mccw.bungeecore.MccwBungeeCore;
    import net.md_5.bungee.api.ChatColor;
    import net.md_5.bungee.api.ProxyServer;
    import net.md_5.bungee.api.connection.ProxiedPlayer;
    import net.md_5.bungee.api.plugin.Listener;
    import net.md_5.bungee.event.EventHandler;
    import net.md_5.bungee.event.EventPriority;

    public class VoteListener implements Listener{
	
	MccwBungeeCore MBC;
	public VoteListener(MccwBungeeCore main) {
		this.MBC = main;
	}
	
	@EventHandler
    public void onVotifierEvent(VotifierEvent e) {
		Vote v = e.getVote();
		
		MBC.getLogger().info(v.getUsername());
		ProxiedPlayer player = ProxyServer.getInstance().getPlayer(v.getUsername());
		if(player != null){
			ProxyServer.getInstance().broadcast(MccwBungeeCore.Prefix + ChatColor.GOLD + v.getUsername() + " 投票了" + ChatColor.AQUA.toString() + ChatColor.BOLD + "MCCW" + ChatColor.GOLD + "伺服器");
	    }
     }

Dont care about the chinese lol
P.S. i have register the listener
i remeber those code worked at pass untill something update 
As me changed to build NuVotifier with maven, or an bungee update, it borken
i also tried an backup from old that doesnt use maven build up , and it still not work

Maven repo is using 2.3.4 but plugin is using 2.3.6-pre
i have also tried back to old version still not work

Any Idea?

Edit:
Tryed Back to 1.11 Version of Bungee, Still get the Error
and the Event still dont fire

**Comment by Ichbinjoe** [comment]
mkcoldwolf, I find this odd tht the event isn't firing. Could you send more of your logs?

For reference, our Bungeecord version of NuVotifier runs the following code:

```
    @Override
    public void onVoteReceived(Channel channel, final Vote vote, VotifierSession.ProtocolVersion protocolVersion) throws Exception {
        if (debug) {
            if (protocolVersion == VotifierSession.ProtocolVersion.ONE) {
                getLogger().info("Got a protocol v1 vote record from " + channel.remoteAddress() + " -> " + vote);
            } else {
                getLogger().info("Got a protocol v2 vote record from " + channel.remoteAddress() + " -> " + vote);
            }
        }

        getProxy().getScheduler().runAsync(this, new Runnable() {
            @Override
            public void run() {
                getProxy().getPluginManager().callEvent(new VotifierEvent(vote));
            }
        });

        if (forwardingMethod != null) {
            getProxy().getScheduler().runAsync(this, new Runnable() {
                @Override
                public void run() {
                    forwardingMethod.forward(vote);
                }
            });
        }
    }
```
So when that message is sent, the event shouldn't be far behind... possibly a bungeecord scheduling problem?

**Comment by Ichbinjoe** [comment]
Tracking in #27

**Comment by jiajunmao** [comment]
I am opening this issue again because similar things are observed on 1.17 bungee. The VoteEvent seems to not fire when NuVotifer prints vote received in console. The code used to listen for the event is as follows

```java
public class VotifierListener implements Listener {

    @EventHandler
    public void onVote(VotifierEvent e) {
        ProxyServer.getInstance().getConsole().sendMessage("A vote received for " + e.getVote().getUsername() + " at time " + e.getVote().getTimeStamp());
    }
}
```
