### ISSUE TITLE
Voting Problem

### ISSUE THREAD

**Issue by Lenti99** [NuVotifier/NuVotifier#54]
Hello, a few weeks ago the voting system was working just fine. However, for some reason, it stopped working. I tried by changing the ip, port and all that but didn't get lucky. Here is an error I found: https://paste.ofcode.org/vmt2UGHf4yeADMwWkN33dK

Thanks

**Comment by Lenti99** [comment]
Another error: https://paste.ofcode.org/mJnKngxYENRtNxj59dtfRS

**Comment by Ichbinjoe** [comment]
these look like jar issues from after a reloaded plugin / server, or maybe a corrupt jar. Did you reload the server before these errors?

**Comment by Ichbinjoe** [comment]
The pastes are no longer accessible. I am closing this issue until new logs are provided. In the future, please use gist or another permanent snippet provider (you can also attach files to the github issue itself!)
