### ISSUE TITLE
BungeeCord voting issue

### ISSUE THREAD

**Issue by da-llama** [NuVotifier/NuVotifier#55]
Hello. I've set up NuVotifier on my Bungeecord server, but when I try to send a test vote it says this in the console: 
https://paste.ofcode.org/hwvGm9B3FZGiWJ7AhwBmit

(Could not process/adress)

**Comment by da-llama** [comment]
And yes, I've checked the key.

**Comment by Ichbinjoe** [comment]
Are you using the key in rsa/ or within the config file (token)

**Comment by da-llama** [comment]
@Ichbinjoe The key in the rsa/

**Comment by da-llama** [comment]
I solved it. I deleted the public key in the rsa folder and restarted the server, which generated the key again.
