### ISSUE TITLE
Votes Not Registering

### ISSUE THREAD

**Issue by RoboJackPlays** [NuVotifier/NuVotifier#63]
I am using the latest Sponge version of Nu Notifier and when the vote is redirected with the Proxy NuVotifier it just states in console: > [00:45:30] [nioEventLoopGroup-3-1/ERROR] [nuvotifier]: Unable to process vote from /172.18.0.1:45666

Any ideas on how to fix this issue?

**Comment by Ichbinjoe** [comment]
Assuming 17.18.0.1 is your proxy, ensure that your v2 tokens match up.
