### ISSUE TITLE
Bungeecord event never get called

### ISSUE THREAD

**Issue by Smove** [NuVotifier/NuVotifier#8]
After a few hours of try, catch and debug this:

In BungeeCord, the "VotifierEvent" never get any results for votes. The listener is loaded by BungeeCord and other EventHandlers in the same listener are working, only the VotifierEvent never get any call.

Console debug:
`00:41:36 [INFORMATION] [NuVotifier] Got a protocol v1 vote record -> Vote (from:MyTestSite username:Smove address:MySuperSexyIpAddress timeStamp:1459118496)`

This never got called:

`@EventHandler
    public void onVote(VotifierEvent event){
        ProxyServer.getInstance().getLogger().log(Level.INFO, "VOTE!");
    }`

VotifierEvent import is _com.vexsoftware.votifier.bungee.events.VotifierEvent_

Tested using:

NuVotifier 2.3.2.2(downloaded from spigotmc.org)
BungeeCord Build 1136
a little test plugin for listener

No more plugins are loaded.

**Comment by minecrafter** [comment]
Unable to reproduce.
