### ISSUE TITLE
votes not registering

### ISSUE THREAD

**Issue by voigtman** [NuVotifier/NuVotifier#9]
To be more accurate - they're not even hitting us at all.
This is new and just began today. Prior today it was business as usual with no issues.
We've tested everything from opening all ports in the firewall and the network to reinstalling nuvotifier But nothing seems to be working. The test site https://ibj.io/v is also having issues - 504 timeout error. I don't know what else to do... any advice?

**Comment by minecrafter** [comment]
https://ibj.io/v is working fine for me. Try again.

**Comment by voigtman** [comment]
it's back up - thank you ...
